name: Update ML-Datasets Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ML-Datasets Repository
        uses: actions/checkout@v2
        with:
          repository: dr-saad-la/ML-Datasets  
          token: ${{ secrets.PAT_DR_SAAD_LA }}  

      - name: Make update_submodule.sh executable
        run: chmod +x ML-Datasets/update_submodule.sh

      - name: Run Submodule Update Script
        run: ./ML-Datasets/update_submodule.sh

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Updated submodule to latest version"
          git push https://$GITHUB_ACTOR:${{ secrets.PAT_DR_SAAD_LA }}@github.com/dr-saad-la/ML-Datasets.git
